runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
beta_settings:
  'source_reference': 'https://github.com/campossrg/personal_portfolio.git#9c6595c367ccee1c43bbc10b47b3908765dd9612'
api_version: 'user_defined'
handlers:
- url: /.*
  script: unused
  login: optional
  secure: optional
